"""add profile fields to match extension

Revision ID: 92cfcfd09a79
Revises: 1353dda5de63
Create Date: 2025-10-01 19:53:48.456763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cfcfd09a79'
down_revision = '1353dda5de63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter_filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ethnicity', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lgbtq', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('work_authorization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('visa_sponsorship', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('veteran', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('veteran')
        batch_op.drop_column('disability')
        batch_op.drop_column('visa_sponsorship')
        batch_op.drop_column('work_authorization')
        batch_op.drop_column('lgbtq')
        batch_op.drop_column('gender')
        batch_op.drop_column('ethnicity')
        batch_op.drop_column('website')
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('cover_letter_filename')

    # ### end Alembic commands ###
