"""added extracted keywords column

Revision ID: c140b4f17d2d
Revises: 5bb798cd679f
Create Date: 2025-08-25 18:41:12.511624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c140b4f17d2d'
down_revision = '5bb798cd679f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_keywords', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('extracted_keywords')

    # ### end Alembic commands ###
